"""Hour 6: the two local audio cues, and the places they are allowed to sound.

Nothing here opens a device or makes a paid call. The cues are generated by
``media_cues`` in-process, and every wiring test drives the real engagement
loop headlessly against the same fakes the Hour 5 tests use.

Two properties are load bearing and are why most of this file exists.

**One speaker, one deadline.** The cues go down the same
``prepare``/``play`` interface as speech and extend the same
``VoiceSession`` quiet deadline, so a cue that is sounding blocks a push-to-talk
exactly as a sentence does, and the goal's closing line waits behind the music.

**Only a verified goal earns the music.** The flourish is armed in the single
branch that turned the light on, so every unsuccessful ending is silent.

    python -m pytest tests -q
"""

from __future__ import annotations

import json
import sys
import time
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

import audio_io  # noqa: E402
import engagement_demo  # noqa: E402
import goal as goal_module  # noqa: E402
import media_cues  # noqa: E402
from voice_turn import VoiceSession  # noqa: E402

from test_goal_action import (  # noqa: E402
    ACK,
    MUSIC,
    STILL_THERE,
    GoalTurn,
    _FrameSensor,
    _inline_goal_session,
    _LocatingBrain,
    _spy_lamp,
    sighting_json,
)
from test_voice_turn import ScriptedSensor, ScriptedTalkKey  # noqa: E402


def _label(wav_bytes: bytes) -> str:
    """What the shared speaker was asked to make: one of three things."""
    if wav_bytes == ACK:
        return "sfx"
    if wav_bytes == MUSIC:
        return "music"
    return "speech"


class CuePlayer:
    """Records every playback with its label and the moment it started.

    The same two-phase interface as the real speaker, and the length it reports
    is honest, so the loop's quiet deadline behaves as it does live. *fail_on*
    is a tuple of WAV payloads whose ``prepare`` raises, which is how the
    failure tests break exactly one cue and nothing else.
    """

    def __init__(self, log=None, cue_seconds=0.0, speech_seconds=0.0, fail_on=()):
        self.log = log if log is not None else []
        self.cue_seconds = cue_seconds
        self.speech_seconds = speech_seconds
        self.fail_on = tuple(fail_on)
        self.played: list[bytes] = []
        #: (label, monotonic time) per playback, for the ordering assertions.
        self.times: list[tuple] = []

    def prepare(self, wav_bytes):
        if wav_bytes in self.fail_on:
            raise audio_io.AudioError("the output device went away")
        seconds = (
            self.cue_seconds if wav_bytes in (ACK, MUSIC) else self.speech_seconds
        )
        return audio_io.PreparedPlayback(
            samples=wav_bytes, sample_rate=16_000, channels=1, seconds=seconds
        )

    def play(self, prepared) -> None:
        label = _label(prepared.samples)
        self.played.append(prepared.samples)
        self.log.append(label)
        self.times.append((label, time.monotonic()))

    def started(self, label: str) -> float:
        """When *label* first sounded. Fails the test if it never did."""
        for played, moment in self.times:
            if played == label:
                return moment
        raise AssertionError(f"{label!r} never played")


def _run_goal(monkeypatch, brain, player, *, speech_seconds=0.0, script=None, press=40):
    """Drive the real loop headlessly through one spoken goal."""
    engagement_demo.run(
        preview=False,
        headless=True,
        sensor=_FrameSensor(script if script is not None else [(True, 8.0)]),
        voice_factory=lambda _lamp: GoalTurn(speech_seconds=speech_seconds),
        talk_key=ScriptedTalkKey(press),
        goals=_inline_goal_session(brain, player),
        player=player,
    )


def _verifying_brain():
    """A brain whose two looks agree: the one path that earns the music."""
    return _LocatingBrain(sighting_json(), json.dumps(STILL_THERE))


# --------------------------------------------------------------------------
# 1. The generated cues themselves
# --------------------------------------------------------------------------


def _decode(wav_bytes):
    pcm, rate, channels, width = audio_io.decode_wav(wav_bytes)
    frames = len(pcm) // (channels * width)
    return pcm, rate, channels, width, frames / float(rate)


def test_the_acknowledgement_is_a_valid_bounded_pcm16_wav():
    pcm, rate, channels, width, seconds = _decode(media_cues.engagement_ack_wav())

    assert rate == media_cues.CUE_SAMPLE_RATE
    assert channels == audio_io.CHANNELS == 1
    assert width == audio_io.SAMPLE_WIDTH == 2
    # A fraction of a second, and provably not silence.
    assert seconds == pytest.approx(media_cues.ENGAGEMENT_ACK_SECONDS, abs=0.01)
    assert 0.0 < seconds < 1.0
    assert max(pcm) > 0


def test_the_success_music_is_a_valid_bounded_pcm16_wav():
    pcm, rate, channels, width, seconds = _decode(media_cues.goal_success_wav())

    assert rate == media_cues.CUE_SAMPLE_RATE
    assert channels == 1
    assert width == audio_io.SAMPLE_WIDTH
    assert seconds == pytest.approx(media_cues.GOAL_SUCCESS_SECONDS, abs=0.01)
    assert 2.0 <= seconds <= 3.0
    assert seconds <= media_cues.MAX_CUE_SECONDS
    assert max(pcm) > 0


def test_the_music_is_clearly_longer_and_clearly_a_tune():
    ack = _decode(media_cues.engagement_ack_wav())[4]
    music = _decode(media_cues.goal_success_wav())[4]

    # Not a near thing: nobody hearing both could take one for the other.
    assert music > ack * 5
    # ...and it is several separately struck notes, at several pitches.
    assert len(media_cues.GOAL_SUCCESS_NOTES) >= 4
    assert len({frequency for frequency, _s in media_cues.GOAL_SUCCESS_NOTES}) >= 3


def test_the_cues_are_deterministic_and_need_no_asset_on_disk():
    assert media_cues.engagement_ack_wav() == media_cues.engagement_ack_wav()
    assert media_cues.goal_success_wav() == media_cues.goal_success_wav()
    assert media_cues.engagement_ack_wav() != media_cues.goal_success_wav()


def test_the_cue_vocabulary_is_two_literal_functions_wide():
    """No registry, no name lookup, no path a model could ever select."""
    source = (Path(__file__).resolve().parent.parent / "src" / "media_cues.py").read_text()

    # Prose about determinism is fine; a call that reads a file or draws a
    # random number is not.
    for forbidden in ("eval(", "exec(", "getattr(", "importlib", "open(", "import random"):
        assert forbidden not in source
    for forbidden in ("import openai", "import character", "import pybullet", "import cv2"):
        assert forbidden not in source
    # Exactly two public callables of its own: one SFX, one tune.
    assert [
        name
        for name, value in vars(media_cues).items()
        if not name.startswith("_")
        and callable(value)
        and getattr(value, "__module__", None) == "media_cues"
    ] == ["engagement_ack_wav", "goal_success_wav"]


def test_an_overlong_cue_is_refused_rather_than_generated():
    """The bound is checked while the buffer is built, not merely documented."""
    rate = media_cues.CUE_SAMPLE_RATE
    too_long = b"\x00\x00" * int((media_cues.MAX_CUE_SECONDS + 1.0) * rate)

    with pytest.raises(RuntimeError, match="outside"):
        media_cues._cue(too_long, rate)


# --------------------------------------------------------------------------
# 2. The engagement acknowledgement
# --------------------------------------------------------------------------


def test_engaging_plays_the_acknowledgement_exactly_once(capsys):
    player = CuePlayer()

    engagement_demo.run(
        preview=False,
        headless=True,
        sensor=ScriptedSensor([(False, 1.0), (True, 3.0)]),
        player=player,
    )
    out = capsys.readouterr().out

    assert "IDLE -> ENGAGED" in out
    assert player.played == [ACK]


def test_every_fresh_engagement_gets_its_own_acknowledgement(capsys):
    player = CuePlayer()

    engagement_demo.run(
        preview=False,
        headless=True,
        sensor=ScriptedSensor([(True, 2.0), (False, 4.0), (True, 2.0)]),
        player=player,
    )
    capsys.readouterr()

    assert player.played == [ACK, ACK]


def test_the_camera_only_demo_still_engages_with_no_speaker_at_all(capsys):
    """No player wired: the motion happens and nothing raises."""
    engagement_demo.run(
        preview=False, headless=True, sensor=ScriptedSensor([(True, 3.0)])
    )

    assert "IDLE -> ENGAGED" in capsys.readouterr().out


def test_a_failing_acknowledgement_is_reported_and_engagement_still_happens(capsys):
    player = CuePlayer(fail_on=(ACK,))

    engagement_demo.run(
        preview=False,
        headless=True,
        sensor=ScriptedSensor([(True, 3.0)]),
        player=player,
    )
    captured = capsys.readouterr()

    assert "IDLE -> ENGAGED" in captured.out
    assert "could not play the engagement acknowledgement" in captured.err
    assert player.played == []


# --------------------------------------------------------------------------
# 3. The success music, and only for a success
# --------------------------------------------------------------------------


def test_a_verified_goal_plays_the_music_between_the_light_and_the_words(
    monkeypatch, capsys
):
    log = _spy_lamp(monkeypatch)
    player = CuePlayer(log=log)
    brain = _verifying_brain()

    _run_goal(monkeypatch, brain, player)
    out = capsys.readouterr().out

    assert "light ON" in out
    timeline = [entry for entry in log if entry in ("look_left", "light_on", "music", "speech")]
    assert timeline == ["look_left", "light_on", "music", "speech"]
    assert player.played == [ACK, MUSIC, b"speech"]
    assert brain.spoken == [goal_module.found_line("mug")]


@pytest.mark.parametrize(
    "sightings",
    [
        # Never found: no turn, no light, no music.
        [sighting_json(found=False, location="unknown")],
        # Found and aimed at, but gone by the second look.
        [sighting_json(), sighting_json(found=False, location="unknown")],
        # Found twice, but it moved to the other side while the head turned.
        [sighting_json(location="left"), sighting_json(location="right")],
    ],
    ids=["never-found", "lost-before-verification", "moved-during-the-turn"],
)
def test_an_unsuccessful_goal_never_plays_the_music(monkeypatch, capsys, sightings):
    log = _spy_lamp(monkeypatch)
    player = CuePlayer(log=log)
    brain = _LocatingBrain(*sightings)

    _run_goal(monkeypatch, brain, player)
    capsys.readouterr()

    assert "light_on" not in log
    assert MUSIC not in player.played
    assert "music" not in log
    # The character still says how it went, and the lamp still ends dark.
    assert player.played[-1] == b"speech"
    assert log[-1] == "light_off"


def test_the_music_waits_until_an_existing_spoken_playback_has_finished(
    monkeypatch, capsys
):
    """The reply accepting the goal claims 30 s -- longer than the whole script."""
    log = _spy_lamp(monkeypatch)
    player = CuePlayer(log=log)
    brain = _verifying_brain()
    goals = _inline_goal_session(brain, player)

    engagement_demo.run(
        preview=False,
        headless=True,
        sensor=_FrameSensor([(True, 8.0)]),
        voice_factory=lambda _lamp: GoalTurn(speech_seconds=30.0),
        talk_key=ScriptedTalkKey(40),
        goals=goals,
        player=player,
    )
    capsys.readouterr()

    # The visual half ran to completion and the light is on...
    assert "light_on" in log
    # ...but the music never went out on top of the reply, and neither did the
    # closing sentence that waits behind it.
    assert player.played == [ACK]
    assert brain.spoken == []
    assert goals.held is True
    assert goals.music_pending is True


def test_the_closing_speech_waits_until_the_music_has_finished(monkeypatch, capsys):
    log = _spy_lamp(monkeypatch)
    player = CuePlayer(log=log, cue_seconds=1.0)
    brain = _verifying_brain()

    _run_goal(monkeypatch, brain, player)
    capsys.readouterr()

    assert player.played == [ACK, MUSIC, b"speech"]
    # A whole second of flourish separates the two, because the music extended
    # the same deadline the closing line waits on.
    assert player.started("speech") - player.started("music") >= 0.95


def test_a_failing_music_cue_is_reported_and_the_goal_still_stands(
    monkeypatch, capsys
):
    """A decoration that failed must not undo a verified goal or its light."""
    log = _spy_lamp(monkeypatch)
    player = CuePlayer(log=log, fail_on=(MUSIC,))
    brain = _verifying_brain()

    _run_goal(monkeypatch, brain, player)
    captured = capsys.readouterr()

    assert "could not play the success music" in captured.err
    assert "light ON" in captured.out
    # The light came on and stayed on until the demo shut down...
    assert log.index("light_on") < log.index("speech")
    assert "light_off" not in log[log.index("light_on"): log.index("speech")]
    # ...and the character still said how it went.
    assert player.played == [ACK, b"speech"]
    assert brain.spoken == [goal_module.found_line("mug")]


def test_the_live_loop_survives_both_cues_failing(monkeypatch, capsys):
    log = _spy_lamp(monkeypatch)
    player = CuePlayer(log=log, fail_on=(ACK, MUSIC))
    brain = _verifying_brain()

    _run_goal(monkeypatch, brain, player, script=[(True, 6.0), (False, 4.0)])
    captured = capsys.readouterr()

    assert "could not play the engagement acknowledgement" in captured.err
    assert "could not play the success music" in captured.err
    # The whole demo ran on, engagement, goal and disengagement alike.
    assert "ENGAGED -> IDLE" in captured.out
    assert "light_on" in log
    assert player.played == [b"speech"]
    assert log[-1] == "light_off"


# --------------------------------------------------------------------------
# 4. One speaker, one microphone, one deadline
# --------------------------------------------------------------------------


@pytest.mark.parametrize(
    "cue, label",
    [(ACK, "engagement acknowledgement"), (MUSIC, "success music")],
    ids=["sfx", "music"],
)
def test_a_cue_extends_the_shared_quiet_deadline_and_shuts_the_microphone(cue, label):
    session = VoiceSession(turn=None, spawn=lambda _work: None)
    player = CuePlayer(cue_seconds=2.0)
    now = time.monotonic()

    assert session.ready(now) is True
    assert engagement_demo._play_cue(player, session, cue, label) is True

    # The lamp is making a noise, so it is "speaking" for this purpose...
    assert session.speaking(time.monotonic()) is True
    assert session.ready(time.monotonic()) is False
    # ...and a push-to-talk request cannot start a turn while it lasts.
    assert session.start(1, time.monotonic()) is False
    assert session.busy is False
    # Once the cue has elapsed, ordinary turns work again.
    assert session.ready(time.monotonic() + 3.0) is True
    assert session.start(1, time.monotonic() + 3.0) is True


def test_a_cue_that_could_not_be_played_holds_the_microphone_shut_for_nothing():
    session = VoiceSession(turn=None, spawn=lambda _work: None)
    player = CuePlayer(cue_seconds=2.0, fail_on=(ACK,))

    assert engagement_demo._play_cue(player, session, ACK, "engagement acknowledgement") is False
    assert session.speaking(time.monotonic()) is False
    assert session.ready(time.monotonic()) is True


def test_a_cue_is_skipped_rather_than_layered_over_the_shared_speaker():
    """Everything else that owns the player keeps the decoration quiet."""
    session = VoiceSession(turn=None, spawn=lambda _work: None)
    now = time.monotonic()
    assert engagement_demo._speaker_free(session, None, now) is True

    # Mid-sentence: the reply is still coming out of the speaker.
    session.mark_speaking(5.0, now)
    assert engagement_demo._speaker_free(session, None, now) is False
    assert engagement_demo._speaker_free(session, None, now + 6.0) is True

    # A goal that still owns the shared player, even after being abandoned.
    goals = _inline_goal_session(_LocatingBrain(sighting_json()))
    goals.request(goal_module.Goal(kind="find_and_light", target="mug"), 1)
    assert engagement_demo._speaker_free(None, goals, now) is False
    goals.finish()
    assert engagement_demo._speaker_free(None, goals, now) is True


def test_the_music_is_armed_only_by_a_goal_that_reached_the_closing_line():
    """`succeeded` is legal from HOLD and nowhere else."""
    goals = _inline_goal_session(_verifying_brain())

    assert goals.succeeded() is False           # no goal at all
    goals.request(goal_module.Goal(kind="find_and_light", target="mug"), 1)
    assert goals.succeeded() is False           # accepted, but nothing verified
    assert goals.music_pending is False

    goals.hold(goal_module.found_line("mug"))
    assert goals.succeeded() is True
    assert goals.music_pending is True

    # Played once, and never twice.
    goals.music_played()
    assert goals.music_pending is False
    # ...and a goal that ends drops the bit with everything else it held.
    goals.succeeded()
    goals.finish()
    assert goals.music_pending is False
